language: python
python:
  - "2.6"
  - "2.7"
env:
  - KOTTI_TEST_DB_STRING=postgresql://postgres@localhost:5432/kotti_testing
  - KOTTI_TEST_DB_STRING=mysql+oursql://root@localhost:3306/kotti_testing
  - KOTTI_TEST_DB_STRING=sqlite://
install:
  - pip install -r https://raw.github.com/Kotti/Kotti/stable/requirements.txt
  - python setup.py dev
  - pip install psycopg2 oursql
before_script:
  - psql -c 'create database kotti_testing;' -U postgres
  - mysql -e 'create database kotti_testing;'
script: py.test
